# Generated by Django 3.1.1 on 2021-02-11 20:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criticality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('full_name', models.CharField(max_length=240)),
                ('location', models.CharField(max_length=120)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2021, 2, 12, 2, 18, 0, 527847))),
                ('status', models.CharField(blank=True, choices=[('not_assigned', 'Not Assigned'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_assigned', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('affected_module', models.CharField(max_length=200)),
                ('risk', models.TextField()),
                ('recommendation', models.TextField()),
                ('year', models.CharField(max_length=6)),
                ('crticality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activities.criticality')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activities.department')),
            ],
        ),
        migrations.CreateModel(
            name='VaptAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.TextField()),
                ('item_count', models.IntegerField(default=1)),
                ('accessibility', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], max_length=20)),
                ('environment', models.CharField(blank=True, choices=[('uat', 'UAT'), ('prod', 'Production')], max_length=20, null=True)),
                ('device_type', models.TextField(blank=True, null=True)),
                ('owner', models.TextField(blank=True, null=True)),
                ('spoc', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.task')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(max_length=16)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_designation', to='activities.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_assigned_by', to='activities.userprofile'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application_assigned_to', to='activities.userprofile'),
        ),
        migrations.CreateModel(
            name='SanitizedUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(default=datetime.datetime(2021, 2, 12, 2, 18, 0, 530791))),
                ('files', models.FileField(upload_to='uploads/sanitized_upload/')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activities.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RestoreTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_restored', models.DateTimeField(default=datetime.datetime(2021, 2, 12, 2, 18, 0, 531548))),
                ('files', models.FileField(upload_to='uploads/restore_upload/')),
                ('restored_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_organization', to='activities.organization'),
        ),
        migrations.CreateModel(
            name='ConfigurationReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host_name', models.TextField()),
                ('item_count', models.IntegerField(default=1)),
                ('device_type', models.TextField(blank=True, null=True)),
                ('owner', models.TextField(blank=True, null=True)),
                ('spoc', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.task')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(max_length=500)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.task')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BulkActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[(None, '----------------'), ('app_sec', 'Penetration Testing'), ('vapt', 'Vulnerability Assessment'), ('config_review', 'Configuration Audit'), ('multiple', 'Multiple Activities')], default=None, max_length=50)),
                ('files', models.FileField(upload_to='uploads/bulk_upload/')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.task')),
            ],
        ),
        migrations.CreateModel(
            name='BackupTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_backedup', models.DateTimeField(default=datetime.datetime(2021, 2, 12, 2, 18, 0, 531177))),
                ('path', models.CharField(max_length=200)),
                ('backedup_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activities.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationSecurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('url', models.URLField(max_length=300)),
                ('item_count', models.IntegerField(default=1)),
                ('category', models.TextField(choices=[('webapp', 'Web Application'), ('webservice', 'Web Service'), ('mobileapp', 'Mobile Application')], max_length=50)),
                ('accessibility', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], max_length=20)),
                ('testing_type', models.TextField(choices=[('blackbox', 'Black Box'), ('greybox', 'Grey Box'), ('whitebox', 'White Box')], max_length=50)),
                ('environment', models.CharField(blank=True, choices=[('uat', 'UAT'), ('prod', 'Production')], max_length=20, null=True)),
                ('development', models.CharField(blank=True, choices=[('inhouse', 'In-House'), ('third_party', 'Third Party')], max_length=20, null=True)),
                ('functionality', models.TextField(blank=True, max_length=500, null=True)),
                ('role_count', models.CharField(blank=True, max_length=200, null=True)),
                ('loc', models.CharField(blank=True, max_length=200, null=True)),
                ('owner', models.TextField(blank=True, null=True)),
                ('spoc', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('critical', models.CharField(choices=[('n', 'No'), ('y', 'Yes')], default='n', max_length=10)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.task')),
            ],
        ),
    ]
