# Generated by Django 3.1.1 on 2020-10-14 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('full_name', models.CharField(max_length=240)),
                ('location', models.CharField(max_length=120)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('not_assigned', 'Not Assigned'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_assigned', max_length=100)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_assigned_by', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application_assigned_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VaptAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.TextField(null=True)),
                ('accessibility', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], max_length=20, null=True)),
                ('owner', models.TextField(null=True)),
                ('spoc', models.TextField(null=True)),
                ('device_type', models.TextField(null=True)),
                ('environment', models.CharField(choices=[('uat', 'UAT'), ('prod', 'Production')], max_length=20, null=True)),
                ('location', models.TextField(null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='uploads/vulnerability_assessment/')),
                ('comments', models.TextField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.task')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=16)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_designation', to='activities.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_organization', to='activities.organization'),
        ),
        migrations.CreateModel(
            name='ConfigurationReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.TextField(null=True)),
                ('owner', models.TextField(null=True)),
                ('spoc', models.TextField(null=True)),
                ('device_type', models.TextField(null=True)),
                ('location', models.TextField(null=True)),
                ('host_count', models.IntegerField(null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='uploads/configuration_review/')),
                ('comments', models.TextField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.task')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(max_length=500)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.task')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationSecurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('category', models.TextField(choices=[('webapp', 'Web Application'), ('webservice', 'Web Service'), ('mobapp', 'Mobile Application')], max_length=50)),
                ('owner', models.TextField(null=True)),
                ('spoc', models.TextField(null=True)),
                ('url', models.URLField(max_length=300, null=True)),
                ('role_count', models.CharField(max_length=200, null=True)),
                ('functionality', models.TextField(max_length=500, null=True)),
                ('testing_type', models.TextField(choices=[('blackbox', 'Black Box'), ('greybox', 'Grey Box'), ('whitebox', 'White Box')], max_length=50)),
                ('accessibility', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], max_length=20)),
                ('development', models.CharField(choices=[('inhouse', 'In-House'), ('third_party', 'Third Party')], max_length=20, null=True)),
                ('environment', models.CharField(choices=[('uat', 'UAT'), ('prod', 'Production')], max_length=20, null=True)),
                ('page_count', models.IntegerField(null=True)),
                ('loc', models.CharField(max_length=200, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='uploads/penetration_testing/')),
                ('comments', models.TextField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.task')),
            ],
        ),
    ]
