# Generated by Django 3.0.8 on 2020-09-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsecurity',
            name='status',
            field=models.CharField(choices=[('Not Assigned', 'Not Assigned'), ('Rejected', 'Rejected'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='configurationreview',
            name='status',
            field=models.CharField(choices=[('Not Assigned', 'Not Assigned'), ('Rejected', 'Rejected'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vaptassessment',
            name='status',
            field=models.CharField(choices=[('Not Assigned', 'Not Assigned'), ('Rejected', 'Rejected'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=100),
        ),
    ]
