# Generated by Django 3.1.1 on 2020-10-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationsecurity',
            name='backend_technologies',
        ),
        migrations.RemoveField(
            model_name='applicationsecurity',
            name='business_purpose',
        ),
        migrations.RemoveField(
            model_name='applicationsecurity',
            name='credentials',
        ),
        migrations.RemoveField(
            model_name='applicationsecurity',
            name='frontend_technologies',
        ),
        migrations.RemoveField(
            model_name='applicationsecurity',
            name='host_server',
        ),
        migrations.RemoveField(
            model_name='configurationreview',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vaptassessment',
            name='name',
        ),
        migrations.AddField(
            model_name='applicationsecurity',
            name='accessibility',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicationsecurity',
            name='development',
            field=models.CharField(choices=[('inhouse', 'In-House'), ('third_party', 'Third Party')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicationsecurity',
            name='environment',
            field=models.CharField(choices=[('uat', 'UAT'), ('prod', 'Production')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicationsecurity',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='uploads/penetration_testing/'),
        ),
        migrations.AddField(
            model_name='applicationsecurity',
            name='owner',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='applicationsecurity',
            name='page_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='applicationsecurity',
            name='spoc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='applicationsecurity',
            name='testing_type',
            field=models.TextField(choices=[('blackbox', 'Black Box'), ('greybox', 'Grey Box'), ('whitebox', 'White Box')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='configurationreview',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='uploads/configguration_review/'),
        ),
        migrations.AddField(
            model_name='configurationreview',
            name='ip_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='configurationreview',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='configurationreview',
            name='owner',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='configurationreview',
            name='spoc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vaptassessment',
            name='accessibility',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vaptassessment',
            name='environment',
            field=models.CharField(choices=[('uat', 'UAT'), ('prod', 'Production')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vaptassessment',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='uploads/vulnerability_assessment/'),
        ),
        migrations.AddField(
            model_name='vaptassessment',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vaptassessment',
            name='owner',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vaptassessment',
            name='spoc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='applicationsecurity',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationsecurity',
            name='functionality',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='applicationsecurity',
            name='loc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicationsecurity',
            name='role_count',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicationsecurity',
            name='url',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='configurationreview',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configurationreview',
            name='device_type',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='configurationreview',
            name='host_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vaptassessment',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaptassessment',
            name='device_type',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vaptassessment',
            name='ip_address',
            field=models.TextField(null=True),
        ),
    ]
