# Generated by Django 3.1.1 on 2020-10-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20201014_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsecurity',
            name='development',
            field=models.CharField(blank=True, choices=[('inhouse', 'In-House'), ('third_party', 'Third Party')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicationsecurity',
            name='environment',
            field=models.CharField(blank=True, choices=[('uat', 'UAT'), ('prod', 'Production')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicationsecurity',
            name='owner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationsecurity',
            name='spoc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
