# Generated by Django 3.1.1 on 2020-10-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20201014_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsecurity',
            name='page_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
