# Generated by Django 3.0.8 on 2020-09-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20200917_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='organization',
        ),
        migrations.AlterField(
            model_name='applicationsecurity',
            name='other_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationsecurity',
            name='status',
            field=models.CharField(choices=[('Not Assigned', 'Not Assigned'), ('Rejected', 'Rejected'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Not Assigned', max_length=100),
        ),
    ]
