# Generated by Django 3.1.1 on 2020-11-07 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20201014_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[(None, '----------------'), ('app_sec', 'Application Security'), ('vapt', 'Vulnerability Assessment'), ('config_review', 'Configuration Audit')], default=None, max_length=50)),
                ('files', models.FileField(upload_to='uploads/bulk_upload/')),
            ],
        ),
        migrations.CreateModel(
            name='Criticality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='applicationsecurity',
            name='category',
            field=models.TextField(choices=[('webapp', 'Web Application'), ('webservice', 'Web Service'), ('mobileapp', 'Mobile Application')], max_length=50),
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('affected_module', models.CharField(max_length=200)),
                ('risk', models.TextField()),
                ('recommendation', models.TextField()),
                ('year', models.CharField(max_length=6)),
                ('crticality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activities.criticality')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activities.department')),
            ],
        ),
    ]
