# Generated by Django 3.1.1 on 2020-10-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20201013_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsecurity',
            name='category',
            field=models.TextField(choices=[('webappext', 'Web Application External'), ('webappint', 'Web Application Internal'), ('webserint', 'Web Service External'), ('webserint', 'Web Service Internal'), ('mobapp', 'Mobile Application')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='configurationreview',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='uploads/configuration_review/'),
        ),
    ]
