# Generated by Django 3.1.1 on 2020-11-18 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20201107_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkactivity',
            name='activity',
        ),
        migrations.AddField(
            model_name='bulkactivity',
            name='category',
            field=models.CharField(choices=[(None, '----------------'), ('app_sec', 'Penetration Testing'), ('vapt', 'Vulnerability Assessment'), ('config_review', 'Configuration Audit')], default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='bulkactivity',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.task'),
        ),
    ]
