# Generated by Django 3.1.1 on 2020-11-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_auto_20201118_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkactivity',
            name='category',
            field=models.CharField(choices=[(None, '----------------'), ('app_sec', 'Penetration Testing'), ('vapt', 'Vulnerability Assessment'), ('config_review', 'Configuration Audit')], default=None, max_length=50, null=True),
        ),
    ]
